name: Cypress CI

on:
  push:
    branches:
      - main
      - 66-e2e-테스트-유저-플로우-및-서비스-로직-테스트
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn dev
          wait-on: "http://localhost:5173"
          browser: chrome # or any browser you want to run tests in
        env:
          baseUrl: ${{ secrets.baseUrl }}
          sellerId: ${{ secrets.sellerId }}
          sellerPw: ${{ secrets.sellerPw }}
          registerId: ${{ secrets.registerId }}
          registerPW: ${{ secrets.registerPW }}
          userId: ${{ secrets.userId }}
          userPw: ${{ secrets.userPw }}
          supabase_auth_url: ${{ secrets.supabase_auth_url }}
          supabase_db_url: ${{ secrets.supabase_db_url }}

      - name: Upload Cypress screenshots and videos (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            ./cypress/screenshots
            ./cypress/videos
