name: Test CI 자동화

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Set environment variables
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_SECRET_KEY=${{ secrets.VITE_SUPABASE_SECRET_KEY }}" >> $GITHUB_ENV
          echo "VITE_BUCKET_BASE_URL=${{ secrets.VITE_BUCKET_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_OAUTH_REDIRECT_URI=${{ secrets.VITE_OAUTH_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "VITE_STORE_ID=${{ secrets.VITE_STORE_ID }}" >> $GITHUB_ENV
          echo "VITE_CHANNEL_KEY_TOSS=${{ secrets.VITE_CHANNEL_KEY_TOSS }}" >> $GITHUB_ENV
          echo "VITE_PORTONE_SECRET_KEY=${{ secrets.VITE_PORTONE_SECRET_KEY }}" >> $GITHUB_ENV
          echo "VITE_USER_SELLER_ID=${{ secrets.VITE_USER_SELLER_ID }}" >> $GITHUB_ENV
          echo "VITE_USER_SELLER_PASSWORD=${{ secrets.VITE_USER_SELLER_PASSWORD }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Vitest Run
        run: yarn test:run

      - name: Create cypress.env.json
        run: |
          echo '{
            "CYPRESS_BASEURL": "${{ secrets.CYPRESS_BASEURL }}",
            "CYPRESS_SELLERID": "${{ secrets.CYPRESS_SELLERID }}",
            "CYPRESS_SELLERPW": "${{ secrets.CYPRESS_SELLERPW }}",
            "CYPRESS_REGISTERID": "${{ secrets.CYPRESS_REGISTERID }}",
            "CYPRESS_REGISTERPW": "${{ secrets.CYPRESS_REGISTERPW }}",
            "CYPRESS_USERID": "${{ secrets.CYPRESS_USERID }}",
            "CYPRESS_USERPW": "${{ secrets.CYPRESS_USERPW }}",
            "CYPRESS_SUPABASE_AUTH_URL": "${{ secrets.CYPRESS_SUPABASE_AUTH_URL }}",
            "CYPRESS_SUPABASE_DB_URL": "${{ secrets.CYPRESS_SUPABASE_DB_URL }}"
          }' > cypress.env.json

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: yarn dev
          wait-on: "http://localhost:5173"
          browser: chrome

      - name: Upload Cypress screenshots and videos (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            ./cypress/screenshots
            ./cypress/videos
